### ISSUE TITLE
KeyError: 'custom_automation_id'

### ISSUE THREAD

**Issue by ccastaneda1218** [sinanerdinc/robotframework-testrail#1]
Hello, Im receiving below error 

`api_request_handler.py", line 301, in check_missing_test_cases_ids
    aut_case_id = case["custom_automation_id"]
KeyError: 'custom_automation_id'
`

**Comment by sinanerdinc** [comment]
You must add a tag named CID to your test scenarios. Example CID=100 , the value 100 here represents the id of the scenario that you have created in Testrail.

Example:

```
*** Test Cases ***
Example Scenario
    [Tags]  CID=100
    log to console    Hello
```

**Comment by ccastaneda1218** [comment]
Thanks it worked!
